#!/bin/bash

cd ~/public_html/
chmod 711 LinkedIn
cd LinkedIn
chmod 711 front_end cgi-bin
cd front_end
chmod 711 css images
chmod 644 css/* images/*
cd ..
chmod 644 index.html
cd cgi-bin
chmod 700 *.cgi *.py
